name: build-and-push-docker

on:
  workflow_dispatch: # allows the workflow to be run manually when desired
    branches:
      - main
  # schedule: # runs this workflow at the scheduled time (uses UTC, adjust for your timezone)
  #   - cron: "00 1 * * *" # at 06:30 AM daily (01:00 AM UTC, add 5:30 in UTC to get the IST)
  push:
    branches:
      - main

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Read version from file
        id: version
        run: echo "VERSION=$(cat VERSION)" >> $GITHUB_ENV

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ secrets.GHCR_USERNAME }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            amit94302/deluge2qbit:${{ env.VERSION }}
            amit94302/deluge2qbit:latest
            ghcr.io/amit94302/deluge2qbit:${{ env.VERSION }}
            ghcr.io/amit94302/deluge2qbit:latest
